### ISSUE TITLE
进程同步bug

### ISSUE THREAD

**Issue by Enzyme125** [Enzyme125/meteor#10]
现在进程十分离谱，画图进程和软件进程无法正常交互。
画图一段时间过后图像可能会**逐渐消失**

**Comment by Enzyme125** [comment]
@cnwangjihe

**Comment by Enzyme125** [comment]
在https://github.com/Enzyme125/meteor/commit/45e091d07f05bdc9738730ddeacb109ef05a2b48中被解决，取消了不同步的pause代码

**Comment by cnwangjihe** [comment]
大概不需要进程间同步，因为没有任何共享内存，controller和graphics跑在同一个子进程里，不是多进程造成的问题，且在本机无法复现（10min
