### ISSUE TITLE
长期任务

### ISSUE THREAD

**Issue by Enzyme125** [Enzyme125/meteor#2]
@Enzyme125 

- [x] recorder的wav读取，可选择读音频/读声卡

- [x] analyzer的传统判断算法

@cnwangjihe 

- [ ] 屏幕录制
- [ ] 数据上传

**Comment by Enzyme125** [comment]
今天的开发任务咕了。

**Comment by cnwangjihe** [comment]
差评如潮

**Comment by Enzyme125** [comment]
实际完成时间12月7 日》》》？？？
