### ISSUE TITLE
音频种类的不同要求分析器使用不同的模式处理

### ISSUE THREAD

**Issue by TOMGY** [Enzyme125/meteor#5]
这与信号源的内容和接收端的解调模式有关。
1.如果是FM电台，使用FM模式解调，得到的音频可能（因为我们还没实际听过）是流星来时有人声、乐音或者静音，其余时候是白噪音。
2.如果是FM电台，使用CW模式解调，得到的音频可能（因为我们还没实际听过）是流星来时有类似高倍快进的声音，其余时候是白噪音。
3.如果是模拟电视伴音信号，使用CW模式解调，得到的音频是流星来时有特定频率的声音，其余时候是白噪音。
4.如果是信标台，播报内容是莫尔斯电码形式的，使用CW或者USB、LSB、或者DSB模式解调，得到的音频可能也是流星来时有特定频率的声音，且有断断续续，其余时候是白噪音。

所以分析器后期需要设置不同的模式，以应对不同的情况。建议先做第3或第4种，因为比较简单，好做。
然后再做第2种。带有这几种模式的分析器做好了后，就可以用于蹲台了。

**Comment by Enzyme125** [comment]
没有实际数据，没法测试啊，我们也不知道你所说的声音会是什么

**Comment by TOMGY** [comment]
> 没有实际数据，没法测试啊，我们也不知道你所说的声音会是什么

先把网上的录音分析了吧，那个是实际数据，如果我们选的台类型一样的话

**Comment by TOMGY** [comment]
可以做一个最基本的处理第3种的，顺便把截取音频的程序做了，然后就知道是啥声音了，毕竟现在还找不到台，没法获得在哈尔滨的数据。
总的思路就是慢慢探索，不断升级改版。前面的工作都是给后面做铺垫，目前只能这样，毕竟你们也没有啥想法，不知道如何入手的话，先做能做的吧。

**Comment by Enzyme125** [comment]
截取音频的程序已经做好了。

**Comment by TOMGY** [comment]
太棒了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Enzyme125&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月28日(星期三) 下午3:42
收件人:&nbsp;&quot;Enzyme125/meteor&quot;<meteor@noreply.github.com&gt;;
抄送:&nbsp;&quot;TOMGY&quot;<3123196845@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Enzyme125/meteor] 音频种类的不同要求分析器使用不同的模式处理 (#5)
